#!/bin/sh
# Usage: prune-dirs <path>...
# Remove empty directories under and including <path>s.

find "$@" -type d -empty -depth | xargs rmdir

# https://github.com/rtomayko/dotfiles/blob/rtomayko/bin/prune-dirs
