#!/bin/bash

# This function remove comments and empty lines.

if [[ ! -z <&0 ]]; then
  grep '^[^#|^$|^ *$]' <&0
else [[ ! -z $1 ]]; then
  grep '^[^#|^$|^ *$]' $1
else
  >&2 echo "ERROR: You must stdin a text or set files as arguments"
fi


